{"name": "test_fas", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 2\n  +4\n  -2", "trace": "def test_fas():\n>       assert 4==2\nE       assert 4 == 2\nE         +4\nE         -2\n\ntest3\\test_f.py:5: AssertionError"}, "start": 1637328971576, "stop": 1637328971576, "uuid": "f4aada01-1942-4565-ae2b-f64e90ee1c65", "historyId": "624735fd7bd3ee37923314f587439c7e", "testCaseId": "1e5ac1df2961cc6c18584f86835cd527", "fullName": "test3.test_f#test_fas", "labels": [{"name": "parentSuite", "value": "test3"}, {"name": "suite", "value": "test_f"}, {"name": "host", "value": "CYHD-L-0025"}, {"name": "thread", "value": "11164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test3.test_f"}]}